language: r
cache: packages

r:
  - release
#  - devel

sudo: false

r_packages:
  - vegan

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

# r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always

