all: cepread
F77=`"${R_HOME}/bin/R" CMD config F77`
FLIBS=`"${R_HOME}/bin/R" CMD config FLIBS`
FFLAGS=`"${R_HOME}/bin/R" CMD config FFLAGS`
cepread: cepin.f
	$(F77) $(FLIBS) $(FFLAGS) cepin.f -o cepread
