F77:=`"${R_HOME}/bin/R" --arch i386 CMD config F77`
FLIBS:=`"${R_HOME}/bin/R" --arch i386 CMD config FLIBS`
FFLAGS:=`"${R_HOME}/bin/R" --arch i386 CMD config FFLAGS`
cepread: cepin.f
	$(F77) $(FLIBS) $(FFLAGS) cepin.f -o cepread
